name: Destroy Infrastructure
on:
  workflow_dispatch:
    inputs:
      module:
        type: string
        description: 'Module to destroy'
        required: true
      resource_name:
        type: string
        description: 'Name of the resource to destroy'
        required: true

permissions:
  contents: read
    
env:
  TF_PLAN_FILE: ${{ github.sha }}.tfplan
  aws_region: ${{ secrets.AWS_REGION }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}

jobs:
  destroy-plan:
    name: "Plan Destroy ${{ github.event.inputs.module }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Backend Configuration
        run: |
          cat > backend.tf << EOF
          terraform {
            backend "s3" {
              bucket         = "$BUCKET_TF_STATE"
              key            = "${{ github.event.inputs.module }}/${{ github.event.inputs.resource_name }}.tfstate"
              region         = "$aws_region"
              encryption     = true
              dynamodb_table = "${{ github.event.inputs.module }}-terraform-lock"
            }
          }
          EOF
        working-directory: modules/${{ github.event.inputs.module }}

      - name: Terraform Init
        run: terraform init
        working-directory: modules/${{ github.event.inputs.module }}

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out ${{ env.TF_PLAN_FILE }} -var-file="${{ github.event.inputs.module }}.tfvars"
        working-directory: modules/${{ github.event.inputs.module }}

      - name: Upload Terraform Destroy Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan-destroy-${{ github.event.inputs.module }}
          path: modules/${{ github.event.inputs.module }}/${{ env.TF_PLAN_FILE }}
        
  destroy-apply:
    name: "Apply Destroy ${{ github.event.inputs.module }}"
    runs-on: ubuntu-latest
    needs: destroy-plan
    environment:
      name: ${{ github.event.inputs.module }}-${{ github.event.inputs.resource_name }}-destroy
      url: ${{ steps.environment.outputs.environment_url }}
            
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
                
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7
                
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Backend Configuration
        run: |
          cat > backend.tf << EOF
          terraform {
            backend "s3" {
              bucket         = "$BUCKET_TF_STATE"
              key            = "${{ github.event.inputs.module }}/${{ github.event.inputs.resource_name }}.tfstate"
              region         = "$aws_region"
              encryption     = true
              kms_key_id     = "${{ secrets.BACKEND_AWS_KMS_KEY_ID }}"
              dynamodb_table = "${{ secrets.BACKEND_DYNAMODB_TABLE }}-terraform-lock"
            }
          }
          EOF
        working-directory: modules/${{ github.event.inputs.module }}

      - name: Download Terraform Plan Destroy
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan-destroy-${{ github.event.inputs.module }}
          path: modules/${{ github.event.inputs.module }}

      - name: Terraform Init
        run: terraform init
        working-directory: modules/${{ github.event.inputs.module }}

      - name: Terraform Apply Destroy
        run: terraform apply -auto-approve ${{ env.TF_PLAN_FILE }}
        working-directory: modules/${{ github.event.inputs.module }}
        
      - name: Output Destruction Info
        run: |
          echo "environment_url=https://console.aws.amazon.com/console/home?region=${{ secrets.AWS_REGION }}" >> $GITHUB_OUTPUT
          echo "Successfully destroyed ${{ github.event.inputs.module }} - ${{ github.event.inputs.resource_name }}"
        id: environment