name: Infrastructure Management
on:
  workflow_dispatch:

jobs:
  router:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Trigger selected workflow
        run: |
          gh workflow run static-workflow.yml \
            -f module=default-module \
            -f resource_name=default-resource
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}